/**
 * Golden fixture tests — every value generated by legacy/ (frozen 4.0.0 code,
 * see scripts/generate-goldens.js) must be reproduced by the current target.
 *
 * Deterministic pins: scrypt key, decrypted seed, addresses, private keys,
 * unsigned/signed tx hex, upgrade outputs. Ciphertext blobs are nonce-random
 * and checked by decryptability instead.
 */
import { describe, it, expect } from 'vitest';
import { createRequire } from 'node:module';
import { KeyStore, Upgrade, Signing, TxUtils, TARGET } from '../unit/target';

const require = createRequire(import.meta.url);
const golden = require('./generated/vault-4.0.0.json');

function hex(u8: Uint8Array): string {
  return Buffer.from(u8).toString('hex');
}

describe(`Golden: vault-4.0.0 [target=${TARGET}]`, () => {
  it('scrypt KDF reproduces the pinned derived key', async () => {
    const dk = await new Promise<Uint8Array>((resolve, reject) => {
      KeyStore.deriveKeyFromPasswordAndSalt(golden.kdf.password, golden.kdf.salt, (err: unknown, k?: Uint8Array) =>
        err ? reject(err) : resolve(k as Uint8Array),
      );
    });
    expect(hex(dk)).toBe(golden.kdf.pwDerivedKeyHex);
  });

  it('scrypt KDF default-salt overload still works', async () => {
    const dk = await new Promise<Uint8Array>((resolve, reject) => {
      KeyStore.deriveKeyFromPasswordAndSalt('pw', (err: unknown, k?: Uint8Array) =>
        err ? reject(err) : resolve(k as Uint8Array),
      );
    });
    const dkExplicit = await new Promise<Uint8Array>((resolve, reject) => {
      KeyStore.deriveKeyFromPasswordAndSalt('pw', KeyStore.DEFAULT_SALT, (err: unknown, k?: Uint8Array) =>
        err ? reject(err) : resolve(k as Uint8Array),
      );
    });
    expect(hex(dk)).toBe(hex(dkExplicit));
    expect(dk.length).toBe(32);
  });

  it('the serialized golden vault deserializes and decrypts', () => {
    const ks = KeyStore.deserialize(golden.vault.serialized);
    const pw = Uint8Array.from(Buffer.from(golden.kdf.pwDerivedKeyHex, 'hex'));

    expect(ks.getSeed(pw)).toBe(golden.vault.decryptedSeed);
    expect(ks.getAddresses()).toEqual(golden.firstFiveAddresses);
    expect(ks.hdIndex).toBe(golden.vault.hdIndexAfter);
  });

  it('createVault + generateNewAddress reproduces addresses and private keys', async () => {
    const input = golden.vault.input;
    const ks = await new Promise<any>((resolve, reject) => {
      KeyStore.createVault(
        { password: input.password, seedPhrase: input.mnemonic, salt: input.salt, hdPathString: input.hdPathString },
        (err: unknown, k?: any) => (err ? reject(err) : resolve(k)),
      );
    });
    const pw = Uint8Array.from(Buffer.from(golden.kdf.pwDerivedKeyHex, 'hex'));
    ks.generateNewAddress(pw, 5);

    expect(ks.getAddresses()).toEqual(golden.firstFiveAddresses);
    for (let i = 0; i < 5; i++) {
      expect(ks.exportPrivateKey(golden.firstFiveAddresses[i], pw)).toBe(golden.firstFivePrivateKeys[i]);
    }
    // The fresh vault's own ciphertext blob must be decryptable (same
    // secretbox format the golden vault uses).
    expect(KeyStore._decryptString(ks.encSeed, pw)).not.toBe(false);
  });

  it('signTx reproduces the 3 pinned legacy transactions (v=27/28, pre-EIP-155)', async () => {
    const input = golden.vault.input;
    const ks = await new Promise<any>((resolve, reject) => {
      KeyStore.createVault(
        { password: input.password, seedPhrase: input.mnemonic, salt: input.salt, hdPathString: input.hdPathString },
        (err: unknown, k?: any) => (err ? reject(err) : resolve(k)),
      );
    });
    const pw = Uint8Array.from(Buffer.from(golden.kdf.pwDerivedKeyHex, 'hex'));
    ks.generateNewAddress(pw, 5);
    const addr = ks.getAddresses()[0];

    for (const c of golden.signedLegacyTxs) {
      const tx = TxUtils.createTx(c.txObject);
      const rawUnsigned = TxUtils.txToHexString(tx);
      expect(rawUnsigned).toBe(c.rawUnsigned);

      const rawSigned = Signing.signTx(ks, pw, rawUnsigned, addr);
      expect(rawSigned).toBe(c.rawSigned);
    }
  });

  it('v1 keystore upgrade reproduces pinned addresses/hdPath/hdIndex', async () => {
    const oldKS = require('../fixtures/lightwallet.json');
    const ser = await new Promise<string>((resolve, reject) => {
      Upgrade.upgradeOldSerialized(JSON.stringify(oldKS), golden.upgrades.v1.password, (err: unknown, s?: string) =>
        err ? reject(err) : resolve(s as string),
      );
    });
    const ks = KeyStore.deserialize(ser);
    expect(ks.getAddresses()).toEqual(golden.upgrades.v1.addresses);
    expect(ks.hdPathString).toBe(golden.upgrades.v1.hdPathString);
    expect(ks.hdIndex).toBe(golden.upgrades.v1.hdIndex);
  });

  it('v2 keystore upgrade reproduces pinned addresses/hdPath/hdIndex', async () => {
    const oldKS = require('../fixtures/lightwalletv2.json');
    const ser = await new Promise<string>((resolve, reject) => {
      Upgrade.upgradeOldSerialized(JSON.stringify(oldKS), golden.upgrades.v2.password, (err: unknown, s?: string) =>
        err ? reject(err) : resolve(s as string),
      );
    });
    const ks = KeyStore.deserialize(ser);
    expect(ks.getAddresses()).toEqual(golden.upgrades.v2.addresses);
    expect(ks.hdPathString).toBe(golden.upgrades.v2.hdPathString);
    expect(ks.hdIndex).toBe(golden.upgrades.v2.hdIndex);
  });
});
